[package]
name = "race-holdem"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 3

[lib]
crate-type = ["cdylib"]

[dependencies]
race-core = "0.0.5"
race-proc-macro = "0.0.5"
borsh = "0.9.3"

[dev-dependencies]
race-test = "0.0.5"
