#[macro_export]
macro_rules! custom_err {
    ($fn:ident) => {
        pub fn $fn() -> race_api::prelude::HandleError {
            race_api::prelude::HandleError::Custom(String::from(stringify!($fn)))
        }
    }
}

custom_err!(internal_player_not_found);
custom_err!(internal_pot_has_no_owner);
custom_err!(internal_malformed_total_bet);
custom_err!(internal_cannot_find_action_player);
custom_err!(internal_player_not_in_game_but_assigned_cards);
custom_err!(internal_failed_to_reveal_board);
custom_err!(internal_unexpected_street);
custom_err!(internal_amount_overflow);
custom_err!(single_player_missing);
custom_err!(single_winner_missing);
custom_err!(next_action_player_missing);
custom_err!(next_button_player_not_found);
custom_err!(next_button_position_not_found);
custom_err!(heads_up_missing_sb);
custom_err!(heads_up_missing_bb);
custom_err!(mplayers_missing_sb);
custom_err!(mplayers_missing_bb);
custom_err!(pot_winner_missing);
custom_err!(not_the_acting_player_to_bet);
custom_err!(not_the_acting_player_to_raise);
custom_err!(not_the_acting_player_to_check);
custom_err!(not_the_acting_player_to_fold);
custom_err!(not_the_acting_player_to_call);
custom_err!(not_the_acting_player);
custom_err!(player_cant_bet);
custom_err!(bet_amonut_is_too_small);
custom_err!(raise_amount_is_too_small);
custom_err!(player_already_betted);
custom_err!(player_cant_check);
custom_err!(player_cant_raise);
custom_err!(cannot_join_full_table);
custom_err!(strongest_hand_not_found);
custom_err!(invalid_hole_cards_number);
custom_err!(first_hole_card_index_missing);
custom_err!(second_hole_card_index_missing);
custom_err!(first_hole_card_error);
custom_err!(second_hole_card_error);
custom_err!(flop_cards_error);
custom_err!(turn_card_error);
custom_err!(river_card_error);
custom_err!(wait_timeout_error_in_settle);
custom_err!(time_card_already_in_use);
custom_err!(no_time_cards);
