[package]
name = "race-holdem-mtt-base"
version = "0.1.0"
edition = "2021"

[dependencies]
race-api.workspace = true
race-proc-macro.workspace = true
borsh.workspace = true

[dev-dependencies]
race-test.workspace = true
anyhow.workspace = true
